Why does the following code...
  
  def execute(block)
    block.call
  end
  
  execute { puts "Hello from insie the execute method!" }
  
Give us the following eror when we run it?

  block.rb1: in `execute': wrong number of arguements (0 for 1) (ArguementError)
  from test.rb:5:in `<main>'
  

-- Answer:

The execute method "block" is missing the "&" sign that allows a block to be
passed as a parameter. 